api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: 'API Phils Ads'
    description: 'API du site'
    version: '1.0.0'
    collection:
            pagination:
                client_enabled: true
                enabled_parameter_name: pagination # optional
                items_per_page: 30 # Default value
    swagger:
             api_keys:
                 apiKey:
                    name: Authorization
                    type: header
    formats:
            jsonld:
                mime_types: ['application/ld+json']

            json:
                mime_types: ['application/json']

            html:
                mime_types: ['text/html']
    error_formats:
            jsonproblem:
                mime_types: ['application/problem+json']

            jsonld:
                mime_types: ['application/ld+json']
    http_cache:
            etag: true
            max_age: 3600
            shared_max_age: 3600