
language: php

php:
- '7.2'

services:
  - mysql

env:
  - SYMFONY_VERSION="4.2.*"

before-install:
- composer self-update

install:
  - composer install
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - php bin/phpunit