# Travis CI Configuration File

language: php

php:
- '7.2'

services:
  - mysql

env:
  - SYMFONY_VERSION="4.2.*"

before-install:
- composer self-update


# Before install, failures in this section will result in build status 'errored'
install:
  - composer install
  - composer require --dev symfony/phpunit-bridge
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

# Script, failures in this section will result in build status 'failed'
script:
  - vendor/bin/simple-phpunit